services:
  db:
    image: mysql:8.0
    container_name: calorizer_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: calorizer_bot
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_URL=jdbc:mysql://db:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_NAME=${BOT_NAME}
      - AI_MODEL_ID=${AI_MODEL_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=${APP_PORT}

volumes:
  db_data: