CREATE DATABASE IF NOT EXISTS `calorizer_db`;
USE `calorizer_db`;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `user_physical_data`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `DATABASECHANGELOG`;
DROP TABLE IF EXISTS `DATABASECHANGELOGLOCK`;
SET FOREIGN_KEY_CHECKS = 1;