-- MySQL Script generated by MySQL Workbench
-- Tue Jul  1 16:38:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `chat_id` BIGINT NOT NULL,
  `payed_acc` TINYINT NOT NULL,
  `language` ENUM("English", "Ukrainian", "Russian", "German") CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`chat_id`),
  UNIQUE INDEX `chatId_UNIQUE` (`chat_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Physical_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Physical_Data` (
  `UserID` BIGINT NOT NULL,
  `age` INT NULL,
  `sex` ENUM("MALE", "FEMALE") CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `body_fat_percent` DOUBLE NULL,
  `height` DOUBLE NULL,
  `weight` DOUBLE NULL,
  `maingoal` ENUM("WEIGHT_LOSS", "Maintenance", "WEIGHT_GAIN") CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  `physical_activity_level` ENUM("SEDENTARY", "LIGHT", "MODERATE", "ACTIVE", "VERY_ACTIVE") CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL,
  PRIMARY KEY (`UserID`),
  INDEX `fk_UserPhysicalData_User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_UserPhysicalData_User`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`User` (`chat_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
